#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : oslo.log
Version  : 3.17.0
Release  : 36
URL      : http://tarballs.openstack.org/oslo.log/oslo.log-3.17.0.tar.gz
Source0  : http://tarballs.openstack.org/oslo.log/oslo.log-3.17.0.tar.gz
Summary  : oslo.log library
Group    : Development/Tools
License  : Apache-2.0
Requires: oslo.log-bin
Requires: oslo.log-python
BuildRequires : GitPython-python
BuildRequires : Jinja2
BuildRequires : Pygments
BuildRequires : Sphinx-python
BuildRequires : bandit-python
BuildRequires : coverage-python
BuildRequires : debtcollector-python
BuildRequires : discover-python
BuildRequires : docutils-python
BuildRequires : extras
BuildRequires : extras-python
BuildRequires : hacking
BuildRequires : imagesize-python
BuildRequires : iso8601-python
BuildRequires : msgpack-python-python
BuildRequires : netaddr
BuildRequires : netifaces-python
BuildRequires : oslo.config
BuildRequires : oslo.context-python
BuildRequires : oslo.serialization-python
BuildRequires : oslo.utils-python
BuildRequires : oslosphinx-python
BuildRequires : oslotest-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pyrsistent-python
BuildRequires : pytest
BuildRequires : python-dateutil-python
BuildRequires : python-dev
BuildRequires : python-mimeparse-python
BuildRequires : python-mock-python
BuildRequires : python3-dev
BuildRequires : reno-python
BuildRequires : setuptools
BuildRequires : tox
BuildRequires : traceback2-python
BuildRequires : unittest2-python
BuildRequires : virtualenv

%description
================================
oslo.log -- Oslo Logging Library
================================

%package bin
Summary: bin components for the oslo.log package.
Group: Binaries

%description bin
bin components for the oslo.log package.


%package python
Summary: python components for the oslo.log package.
Group: Default
Requires: debtcollector-python
Requires: oslo.config
Requires: oslo.context-python
Requires: oslo.serialization-python
Requires: oslo.utils-python
Requires: python-dateutil-python

%description python
python components for the oslo.log package.


%prep
%setup -q -n oslo.log-3.17.0

%build
export LANG=C
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/convert-json

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
